<?php

namespace admin;

class IndexController extends \ControllerBase
{

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
//        die("123");
    }

    public function testAction(){
        $this->returnResult(['code'=>0,'data'=>123]);
    }

}

