<?php

namespace admin;

class IndexController extends \ControllerBase
{

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $menuController = new MenuController();
        $menu = $menuController->getMenuData();


//        var_dump($menu);die;

        $this->view->setVar('menu',$menu);

        $this->assets->addCss("css/bootstrap.min.css");

        $this->assets->addCss("css/bootstrap-responsive.min.css");

        $this->assets->addCss("css/font-awesome.min.css");

        $this->assets->addCss("css/style-metro.css");

        $this->assets->addCss("css/style.css");

        $this->assets->addCss("css/style-responsive.css");

        $this->assets->addCss("css/default.css");

        $this->assets->addCss("css/uniform.default.css");

        $this->assets->addCss("css/jquery.gritter.css");

        $this->assets->addCss("css/daterangepicker.css");

        $this->assets->addCss("css/fullcalendar.css");

        $this->assets->addCss("css/jqvmap.css");

        $this->assets->addCss("css/jquery.easy-pie-chart.css");

        $this->assets->addJs("js/jquery-1.10.1.min.js");

        $this->assets->addJs("js/jquery-migrate-1.2.1.min.js");

        $this->assets->addJs("js/jquery-ui-1.10.1.custom.min.js");

        $this->assets->addJs("js/bootstrap.min.js");

        $this->assets->addJs("js/jquery.slimscroll.min.js");

        $this->assets->addJs("js/jquery.blockui.min.js");

        $this->assets->addJs("js/jquery.cookie.min.js");

        $this->assets->addJs("js/jquery.uniform.min.js");

        $this->assets->addJs("js/jquery.vmap.js");

        $this->assets->addJs("js/jquery.vmap.russia.js");

        $this->assets->addJs("js/jquery.vmap.world.js");

        $this->assets->addJs("js/jquery.vmap.europe.js");

        $this->assets->addJs("js/jquery.vmap.germany.js");

        $this->assets->addJs("js/jquery.vmap.usa.js");

        $this->assets->addJs("js/jquery.vmap.sampledata.js");

        $this->assets->addJs("js/jquery.flot.js");

        $this->assets->addJs("js/jquery.flot.resize.js");

        $this->assets->addJs("js/jquery.pulsate.min.js");

        $this->assets->addJs("js/date.js");

        $this->assets->addJs("js/daterangepicker.js");

        $this->assets->addJs("js/jquery.gritter.js");

        $this->assets->addJs("js/fullcalendar.min.js");

        $this->assets->addJs("js/jquery.easy-pie-chart.js");

        $this->assets->addJs("js/jquery.sparkline.min.js");

        $this->assets->addJs("js/app.js");

        $this->assets->addJs("js/index.js");

        $this->assets->addJs("js/btx.js");



    }

    public function testAction(){
        $this->returnResult(['code'=>0,'data'=>123]);
    }

}

