<?php

class IndexController extends ControllerBase
{

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $this->assets->addCss('css/styles.css');

        $this->assets->addJs('js/jquery.min.js');
//        $this->assets->addJs('js/plugins/forms/ui.spinner.js');
//        $this->assets->addJs('js/plugins/forms/jquery.mousewheel.js');
//        $this->assets->addJs('js/jquery-ui.min.js');
//        $this->assets->addJs("js/plugins/charts/excanvas.min.js");
//        $this->assets->addJs("js/plugins/charts/jquery.flot.js");
//        $this->assets->addJs("js/plugins/charts/jquery.flot.orderBars.js");
//        $this->assets->addJs("js/plugins/charts/jquery.flot.pie.js");
//        $this->assets->addJs("js/plugins/charts/jquery.flot.resize.js");
//        $this->assets->addJs("js/plugins/charts/jquery.sparkline.min.js");
//
//        $this->assets->addJs("js/plugins/tables/jquery.dataTables.js");
//        $this->assets->addJs("js/plugins/tables/jquery.sortable.js");
//        $this->assets->addJs("js/plugins/tables/jquery.resizable.js");
//
//        $this->assets->addJs("js/plugins/forms/autogrowtextarea.js");
//        $this->assets->addJs("js/plugins/forms/jquery.uniform.js");
//        $this->assets->addJs("js/plugins/forms/jquery.inputlimiter.min.js");
//        $this->assets->addJs("js/plugins/forms/jquery.tagsinput.min.js");
//        $this->assets->addJs("js/plugins/forms/jquery.maskedinput.min.js");
//        $this->assets->addJs("js/plugins/forms/jquery.autotab.js");
//        $this->assets->addJs("js/plugins/forms/jquery.chosen.min.js");
//        $this->assets->addJs("js/plugins/forms/jquery.dualListBox.js");
//        $this->assets->addJs("js/plugins/forms/jquery.cleditor.js");
//        $this->assets->addJs("js/plugins/forms/jquery.ibutton.js");
//        $this->assets->addJs("js/plugins/forms/jquery.validationEngine-en.js");
//        $this->assets->addJs("js/plugins/forms/jquery.validationEngine.js");
//
//        $this->assets->addJs("js/plugins/uploader/plupload.js");
//        $this->assets->addJs("js/plugins/uploader/plupload.html4.js");
//        $this->assets->addJs("js/plugins/uploader/plupload.html5.js");
//        $this->assets->addJs("js/plugins/uploader/jquery.plupload.queue.js");
//
//        $this->assets->addJs("js/plugins/wizards/jquery.form.wizard.js");
//        $this->assets->addJs("js/plugins/wizards/jquery.validate.js");
//        $this->assets->addJs("js/plugins/wizards/jquery.form.js");
//
//        $this->assets->addJs("js/plugins/ui/jquery.collapsible.min.js");
//        $this->assets->addJs("js/plugins/ui/jquery.breadcrumbs.js");
//        $this->assets->addJs("js/plugins/ui/jquery.tipsy.js");
//        $this->assets->addJs("js/plugins/ui/jquery.progress.js");
//        $this->assets->addJs("js/plugins/ui/jquery.timeentry.min.js");
//        $this->assets->addJs("js/plugins/ui/jquery.colorpicker.js");
//        $this->assets->addJs("js/plugins/ui/jquery.jgrowl.js");
//        $this->assets->addJs("js/plugins/ui/jquery.fancybox.js");
//        $this->assets->addJs("js/plugins/ui/jquery.fileTree.js");
//        $this->assets->addJs("js/plugins/ui/jquery.sourcerer.js");
//
//        $this->assets->addJs("js/plugins/others/jquery.fullcalendar.js");
//        $this->assets->addJs("js/plugins/others/jquery.elfinder.js");
//
//        $this->assets->addJs("js/plugins/ui/jquery.easytabs.min.js");
//        $this->assets->addJs("js/files/bootstrap.js");
//        $this->assets->addJs("js/files/functions.js");
//
//        $this->assets->addJs("js/charts/chart.js");
//        $this->assets->addJs("js/charts/hBar_side.js");
    }

    public function testAction(){
        $this->returnResult(['code'=>0,'data'=>123]);
    }

}

